### PR TITLE
testing GitHub

### PR DESCRIPTION
**Pull request by Dijkstra7**
Aha, so you first make changes to the map to which the Github master
corresponds and then you make your own branch.
Here I made a test-view where you press the button and a label counts the amount of clicks

### CODE REVIEW

**Comment by Rubenkl** [comment]
You first create a branch from the master, then you edit your own branch,
and finally you pull-request into the master again. Am i right?
Op 20 okt. 2015 4:18 PM schreef "Dijkstra7" notifications@github.com:

**Comment by Dijkstra7** [comment]
well, I first created a branch, but the changes were still saved to the master branch. Then I created a second branch and this one did get the changes. and then i sent a pull request

**Comment by Rubenkl** [comment]
You have to 'enter'  the branch first, otherwise you stay in the master
branch ofcourse.
Op 20 okt. 2015 4:31 PM schreef "Dijkstra7" notifications@github.com:

**Comment by Dijkstra7** [comment]
one, I have no idea how to "enter" a branch. :) but this worked for me. maybe someone can explain Thursday?

**Pull request closed without merging**
